# Generated by Django 4.2.3 on 2023-10-21 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0003_user_terms_n_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pond_number', models.CharField(blank=True, max_length=250, null=True)),
                ('pond_type', models.CharField(blank=True, max_length=250, null=True)),
                ('stoking_date', models.DateTimeField()),
                ('total_aerator_capacity', models.CharField(blank=True, max_length=250, null=True)),
                ('pond_wsa', models.CharField(blank=True, max_length=250, null=True)),
                ('pond_depth', models.CharField(blank=True, max_length=250, null=True)),
                ('estimated_harvest_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ponds', to=settings.AUTH_USER_MODEL)),
                ('last_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_ponds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempreature', models.CharField(blank=True, max_length=250, null=True)),
                ('ph', models.CharField(blank=True, max_length=250, null=True)),
                ('salinity', models.CharField(blank=True, max_length=250, null=True)),
                ('total_ammonia_nitogen', models.CharField(blank=True, max_length=250, null=True)),
                ('nitrite', models.CharField(blank=True, max_length=250, null=True)),
                ('total_dissolved_solids', models.CharField(blank=True, max_length=250, null=True)),
                ('dissolved_oxygen', models.CharField(blank=True, max_length=250, null=True)),
                ('hardness', models.CharField(blank=True, max_length=250, null=True)),
                ('alkalinity', models.CharField(blank=True, max_length=250, null=True)),
                ('unionized_ammonia', models.CharField(blank=True, max_length=250, null=True)),
                ('nitrate', models.CharField(blank=True, max_length=250, null=True)),
                ('vibrio_luminance', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_waterparamter', to=settings.AUTH_USER_MODEL)),
                ('last_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_waterparameter', to=settings.AUTH_USER_MODEL)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_waterparameter', to='farm_app.pond')),
            ],
        ),
        migrations.CreateModel(
            name='ShrimpHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('test_conducted', models.CharField(blank=True, max_length=250, null=True)),
                ('disease_type', models.CharField(blank=True, max_length=250, null=True)),
                ('lab_name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shrimphealth', to=settings.AUTH_USER_MODEL)),
                ('last_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_shrimphealth', to=settings.AUTH_USER_MODEL)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_shrimphealth', to='farm_app.pond')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_count', models.CharField(blank=True, max_length=250, null=True)),
                ('expected_market_rate', models.CharField(blank=True, max_length=250, null=True)),
                ('current_market_rate', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pricing', to=settings.AUTH_USER_MODEL)),
                ('last_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_pricing', to=settings.AUTH_USER_MODEL)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_pricing', to='farm_app.pond')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_supplier', models.CharField(blank=True, max_length=250, null=True)),
                ('feeding_schedule', models.CharField(blank=True, max_length=250, null=True)),
                ('total_feed_consumed', models.CharField(blank=True, max_length=250, null=True)),
                ('feed_price', models.CharField(blank=True, max_length=250, null=True)),
                ('feed_used', models.CharField(blank=True, max_length=250, null=True)),
                ('feed_method', models.CharField(blank=True, max_length=250, null=True)),
                ('feed_conversion_ratio', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_feed', to=settings.AUTH_USER_MODEL)),
                ('last_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_feed', to=settings.AUTH_USER_MODEL)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_feed', to='farm_app.pond')),
            ],
        ),
        migrations.CreateModel(
            name='Biomass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, max_length=250, null=True)),
                ('pl_stocking_size', models.CharField(blank=True, max_length=250, null=True)),
                ('days_of_culture', models.CharField(blank=True, max_length=250, null=True)),
                ('estimated_survival_rate', models.CharField(blank=True, max_length=250, null=True)),
                ('stocking_density', models.CharField(blank=True, max_length=250, null=True)),
                ('seed_supplier', models.CharField(blank=True, max_length=250, null=True)),
                ('avg_body_weight', models.CharField(blank=True, max_length=250, null=True)),
                ('estimated_biomass', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_biomass', to=settings.AUTH_USER_MODEL)),
                ('last_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_biomass', to=settings.AUTH_USER_MODEL)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond', to='farm_app.pond')),
            ],
        ),
    ]
