# Generated by Django 4.2.3 on 2023-10-23 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0005_alter_pond_last_updatedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomass',
            name='last_updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_biomass', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feed',
            name='last_updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_feed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='last_updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_pricing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shrimphealth',
            name='last_updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_shrimphealth', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='last_updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_waterparameter', to=settings.AUTH_USER_MODEL),
        ),
    ]
