# Generated by Django 4.2.3 on 2023-10-26 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0006_alter_biomass_last_updatedby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=250)),
                ('village', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('zip_or_postal_code', models.CharField(max_length=250)),
                ('taluka', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('use_address_for_payment', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=250)),
                ('farm_ownername', models.CharField(max_length=250)),
                ('contact_number', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('CAA_registration_number', models.CharField(max_length=250)),
                ('contact_person_name', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_basicdetails', to=settings.AUTH_USER_MODEL)),
                ('last_updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_basicdetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='biomass',
            name='avg_body_weight',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='biomass',
            name='days_of_culture',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='biomass',
            name='estimated_biomass',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='biomass',
            name='estimated_survival_rate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='biomass',
            name='pl_stocking_size',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='biomass',
            name='seed_supplier',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='biomass',
            name='species',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='biomass',
            name='stocking_density',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_supplier',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_used',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feeding_schedule',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='feed',
            name='total_feed_consumed',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pond',
            name='pond_depth',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pond',
            name='pond_number',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pond',
            name='pond_type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pond',
            name='pond_wsa',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pond',
            name='total_aerator_capacity',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='current_market_rate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='expected_count',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='expected_market_rate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shrimphealth',
            name='disease_type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shrimphealth',
            name='lab_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shrimphealth',
            name='status',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shrimphealth',
            name='test_conducted',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='alkalinity',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='dissolved_oxygen',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='hardness',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='nitrate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='nitrite',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='ph',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='salinity',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='tempreature',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='total_ammonia_nitogen',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='total_dissolved_solids',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='unionized_ammonia',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='vibrio_luminance',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='FarmDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_spread_area', models.CharField(max_length=250)),
                ('water_source', models.CharField(max_length=250)),
                ('energy_source', models.CharField(max_length=250)),
                ('number_of_ponds', models.CharField(max_length=250)),
                ('nursery_avaliability', models.CharField(max_length=250)),
                ('land_water_connectivity', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('address_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressdetails', to='farm_app.addressdetails')),
                ('basic_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basicdetails_farm', to='farm_app.basicdetails')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_farmdetails', to=settings.AUTH_USER_MODEL)),
                ('last_updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_farmdetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='basic_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basicdetails', to='farm_app.basicdetails'),
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_addressdetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='last_updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_addressdetails', to=settings.AUTH_USER_MODEL),
        ),
    ]
